on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n givemeahandfront -g givemeahandfrontabde-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n givemeahandfront --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n givemeahandfront --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n givemeahandfront --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: givemeahandfront.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/giveMeHandFrond-end" -f  "giveMeHandFrond-end/Dockerfile" -t givemeahandfront.azurecr.io/givemeahand:${{ github.sha }} --label dockerfile-path=giveMeHandFrond-end/Dockerfile
        docker push givemeahandfront.azurecr.io/givemeahand:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_givemeahand_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep givemeahand8ba5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace givemeahand8ba5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: givemeahand8ba5
        container-registry-url: givemeahandfront.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: givemeahanddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: givemeahand8ba5
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
          manifests/ingress-3.yml
        images: |
          givemeahandfront.azurecr.io/givemeahand:${{ github.sha }}
        imagepullsecrets: |
          givemeahanddockerauth   
